### PR TITLE
website resources (Hujoe)

### PR DESCRIPTION
**Pull request by HUJOE003**
Let me know if anything needs to be changed! :)

### CODE REVIEW

**Review by ramitaarora — CHANGES_REQUESTED** [review]
Hey Hujoe, this is overall looking really great! There is just a small issue with the images getting a little squished. You can try putting the className in the image div and seeing if that works better (resizing the div, rather than the image)? 

Thank you!!

Screenshot 2024-03-25 at 9 15 49 PM

**Comment by HUJOE003** [comment]
Yes of course!

**Comment by HUJOE003** [comment]
I have made the necessary changes! how does it look now ? Thank you!

**Review by ramitaarora — APPROVED** [review]
Awesome! Nice work :)

Would you mind approving my pull request as well? Thank you!!

**Pull request merged**
