### PR TITLE
Add styles for the article page, refactor CSS ids and class names

### PR DESCRIPTION
**Pull request by valdrinj**
The CSS for the article page has been added and the ids and class names for the news feed and newsletter pages have been refactored so that it does not style elements in other pages.

### CODE REVIEW

**Review by ramitaarora — CHANGES_REQUESTED** [review]
Looking good so far! Can you also just add:

- .article-metadeta h2
- .news-feed-title h3

Thank you!! :)

**Comment by valdrinj** [comment]
@ramitaarora The requested changes have been made, please let me know if you need me to do anything else.

**Comment by ramitaarora** [comment]
@valdrinj ah sorry! I meant to add those to your h2/h3 targets at the top of your CSS sheet. If it works the way you edited it, could we just remove the h2 and h3 at the top? :)

**Comment by valdrinj** [comment]
@ramitaarora Got it, I must have forgotten to remove them. I moved some things around and it should be good now.

**Review by ramitaarora — APPROVED** [review]
Perfect, thank you! :)

**Pull request merged**
